name: python-tutorial-environment
channels:
  - conda-forge
dependencies:
  - numpy=1.16.4
  - scipy=1.3.0
  - matplotlib=3.1.1
  - ipympl=0.3.3
  - pandas=0.25.0
  - ipywidgets=7.5.1
  - rise=5.5.1
  - pip=19.2.1
  - nodejs=12.8.1
  - jupyter_contrib_nbextensions=0.5.1
